package com.example.springboot.Exercise_5;

/**
 * Exercise 1:
 *
 * Create an Entity called Ingredient
 * Create a controller, service, repository
 * Set up CRUD operations for this entity
 * Drop your ingredient table in your db if it still exists to avoid issues/confusion!
 *
 * public class Ingredient {
 *     private Long id;
 *     private String name;
 *     private boolean isVegetarian;
 *     private boolean isVegan;
 *     private boolean isGlutenFree;
 *     private boolean isLactoseFree;
 * }
 */
public class Ingredient {
    private Long id;
    private String name;
    private boolean isVegetarian;
    private boolean isVegan;
    private boolean isGlutenFree;
    private boolean isLactoseFree;

    /**
     * Costractor autoGenerated
     */
    public Ingredient(Long id, String name, boolean isVegetarian, boolean isVegan, boolean isGlutenFree, boolean isLactoseFree) {
        this.id = id;
        this.name = name;
        this.isVegetarian = isVegetarian;
        this.isVegan = isVegan;
        this.isGlutenFree = isGlutenFree;
        this.isLactoseFree = isLactoseFree;
    }

    /**
     * Getter & Setter autoGenerated
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isVegetarian() {
        return isVegetarian;
    }

    public void setVegetarian(boolean vegetarian) {
        isVegetarian = vegetarian;
    }

    public boolean isVegan() {
        return isVegan;
    }

    public void setVegan(boolean vegan) {
        isVegan = vegan;
    }

    public boolean isGlutenFree() {
        return isGlutenFree;
    }

    public void setGlutenFree(boolean glutenFree) {
        isGlutenFree = glutenFree;
    }

    public boolean isLactoseFree() {
        return isLactoseFree;
    }

    public void setLactoseFree(boolean lactoseFree) {
        isLactoseFree = lactoseFree;
    }
}
